In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [2]:
a = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
a = 1 / (1 + np.exp(-a[:]))
print(a[-5:])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [3]:
x=np.array([3,1,4,2,6,1,4,8]) 
y=np.array([5,2,3,12,2,4,17,11])

# a) by using element-wise mutliplication and np.sum
print(np.sum(x * y))

# b) by using np.dot
print(np.dot(x,y))

# c) by using np.matmul and transposition (x.T)
print(np.matmul(x.T,y))


225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [4]:
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2])
theta = np.array([2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65])

y = 1/(1 + np.exp(np.sum(-x[:10]*theta[:10]) - theta[10]))
print(y)


0.2417699832615572


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [5]:
A = np.array([[1,2,1],[3,0,1]])
B = np.array([[0.2],[0.3]])
x = np.transpose([np.array([1,2,3])])
print(np.matmul(A,x) + B)



[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [6]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))
steam_df.head(10)

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

## Merge both MovieLens DataFrames into one

In [7]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [8]:
df = steam_df.loc[(steam_df['behavior-name'] == 'purchase')]
print(df['user-id'].nunique())


12393


**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [9]:
df = steam_df.loc[(steam_df['behavior-name'] == 'purchase') & (steam_df['game-title'] == 'The Elder Scrolls V Skyrim')]
print(df['user-id'].nunique())


717


**Task 7.** How many purchases people made on average?

In [10]:
df = steam_df.loc[(steam_df['behavior-name'] == 'purchase')]
all_purchases = len(df)
unique_purchasers = df['user-id'].nunique()
print(all_purchases/unique_purchasers)


10.45033486645687


**Task 8.** Who bought the most games?

In [11]:
df = steam_df.loc[(steam_df['behavior-name'] == 'purchase')]
print(df['user-id'].value_counts().idxmax())

62990992


**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [12]:
df = steam_df.loc[(steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'play')]
print(df['value'].sum()/df['user-id'].nunique())


104.71093057607091


**Task 10.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [13]:
df = steam_df.loc[(steam_df['behavior-name'] == 'play')]
output = df.groupby('game-title')['value'].sum().reset_index().nlargest(10, 'value').reset_index(drop=True)
print(output)


                                    game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7


**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [14]:
df = steam_df.loc[(steam_df['behavior-name'] == 'play'), ['game-title', 'value']]
df = df.groupby('game-title')['value'].mean().reset_index()
print(df.nlargest(10, 'value').reset_index(drop=True))

                          game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000


**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [15]:
df = steam_df.copy()
df_played = steam_df.loc[(steam_df['behavior-name'] == 'play')]
df_purchased = steam_df.loc[(steam_df['behavior-name'] == 'purchase')]

print(df_purchased.head(10))
print(df_played.head(10))
//tu zmienic i moze odjac tak jak tam dalej
df_purchased_played = df_purchased.assign(result=df_purchased.loc[['game-title','user-id']].isin(df_played.loc[['game-title','user-id']]))
# df_purchased_played = df_purchased_played[df_purchased_played.result == True]

# df_purchased_played = df_purchased_played.drop(columns=['result'])




# df = pd.concat([df, df_purchased_played, df_purchased_played]).drop_duplicates(keep=False)


# df['value'] = np.where(df['behavior-name']=='purchase',0,df['value'] )
# df = df.groupby('game-title')['value'].mean()
# print(df.sort_values(ascending=False).reset_index(drop=True)) 
# df.head(20)



SyntaxError: invalid syntax (Temp/ipykernel_9756/1400483781.py, line 7)

**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [ ]:
def sigmoid(x):
    return 1/(1+np.exp(-(1/100)*x))
df_copy = steam_df.copy()
df_copy2 = df_copy.loc[steam_df['behavior-name']=='play'].copy()

# df_copy = df_copy.loc[steam_df['behavior-name']=='play'].copy()
df_copy2['value'] = df_copy2['value'].map(lambda a: sigmoid(a))

df_copy.update(df_copy2)
df_copy = df_copy.astype({'user-id': 'int32', 'zero': 'int32'} )
print(df_copy.head(10))


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [ ]:
df = ml_df.copy()
df.genres = df.genres.str.split('|')

genre_list = list(set([j for i in df['genres'].tolist() for j in i]))

df_genre = pd.DataFrame({"genre": genre_list, "n_users": 0 })

genres_list = df.genres.tolist()

genres_appeared = [item for sublist in genres_list for item in sublist]

df_genre
for genre in genre_list:
    number = genres_appeared.count(genre)
    df_genre.loc[df_genre['genre'] == genre, 'n_users'] = number
    

  

print(df_genre.sort_values(by ='n_users', ascending=False).reset_index(drop=True))






**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [ ]:
# df = ml_df.copy()
# df.genres = df.genres.str.split('|')

# genre_list = list(set([j for i in df['genres'].tolist() for j in i]))

# df = df[['rating','genres']]
# df = df.explode('genres')

# df = df.groupby('genres').mean().reset_index()
# df.sort_values(by ='rating', ascending=False).reset_index(drop=True)

import numpy as np
df = ml_df.copy()
df.genres = df.genres.str.split('|')

genre_list = list(set([j for i in df['genres'].tolist() for j in i]))

df = df[['rating','genres']]

#explode is for Pandas >= 0.25
newvalues=np.dstack((np.repeat(df.rating.values,list(map(len,df.genres.values))),np.concatenate(df.genres.values)))
df = pd.DataFrame(data=newvalues[0],columns=df.columns)
df["rating"] = pd.to_numeric(df["rating"])

df = df.groupby('genres')['rating'].mean().reset_index()

df = df.rename(columns={"genres": "genre"})
print(df.sort_values(by ='rating', ascending=False).reset_index(drop=True))





**Task 17.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print first 10 in the form: title, average rating, bias.

In [ ]:
Average = ml_df['rating'].mean()
df = ml_df.copy()
df_copy = df.copy().groupby('title').agg({'rating': 'mean'}).reset_index()
df_copy['bias'] = df_copy['rating'].apply(lambda x: x - Average)
df_copy.columns = ['title', 'average_rating', 'bias']
print(df_copy.head(10))



**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print first 10 in the form: user_id, average rating, bias.

In [ ]:

Average = ml_df['rating'].mean()
df = ml_df.copy()
df_copy = df.copy().groupby('userId').agg({'rating': 'mean'}).reset_index()
df_copy['bias'] = df_copy['rating'].apply(lambda x: x - Average)
df_copy.columns = ['title', 'average_rating', 'bias']
print(df_copy.head(10))

**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task.

In [64]:
user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))
df = ml_df.copy()

matrix = np.zeros((10, 10))

df2 = df.loc[df['userId'].isin(user_ids) & df['movieId'].isin(movie_ids)]
titles = df.loc[df['movieId'].isin(movie_ids)].sort_values('movieId').title.drop_duplicates().values.tolist()


id_title = list(zip(df2['userId'],df2['movieId']))

for element in id_title:
    x = user_ids.index(element[0])
    y = movie_ids.index(element[1])
    matrix[x][y] = 1

df = pd.DataFrame(matrix, columns=titles, index =user_ids )
print(df)





     Father of the Bride (1950)  Matrix, The (1999)  Howards End (1992)  \
11                          0.0                 0.0                 0.0   
277                         0.0                 0.0                 0.0   
286                         0.0                 1.0                 0.0   
357                         0.0                 0.0                 0.0   
414                         0.0                 1.0                 0.0   
428                         0.0                 1.0                 0.0   
470                         0.0                 0.0                 0.0   
487                         0.0                 1.0                 0.0   
543                         0.0                 1.0                 0.0   
544                         0.0                 0.0                 0.0   

     Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)  \
11                                                 0.0                         
277           

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix for the MovieLens dataset. Print the submatrix of first 10 rows and 10 columns.

In [20]:
df = ml_df.copy()
df = df.pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0)
array = np.array(df.iloc[0:10,0:10])
col = np.zeros((10,1))
row = np.zeros((1,11))
array = np.append(col, array, axis=1)
array = np.vstack([row,array])
b = array[:-1,:-1]
#had to add row and column with zeros for some reason
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [104]:
df = ml_df.copy()
n = df.userId.nunique()
matrix = np.zeros((n+1, n+1))
indices = np.triu_indices_from(matrix)

users = []
for i in range(1,n+1):
    user_i = df.loc[df['userId']==i,['movieId']]
    user_i = user_i['movieId'].values.tolist()
    users.append(user_i)
    
    
for i in range(1, n+1):
    for j in range(i, n+1):
        common_elements = np.intersect1d(users[i-1], users[j-1])
        matrix[i][j] = len(common_elements)
        
i_lower = np.tril_indices(n, -1)
matrix[i_lower] = matrix.T[i_lower] 
        
print(matrix[:10, :10])


        




[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 232.   2.   7.  45.  13.  33.  26.  15.   5.]
 [  0.   2.  29.   0.   1.   1.   2.   3.   1.   0.]
 [  0.   7.   0.  39.   1.   1.   3.   0.   1.   0.]
 [  0.  45.   1.   1. 216.  12.  27.  22.   9.   1.]
 [  0.  13.   1.   1.  12.  44.  36.   9.  19.   0.]
 [  0.  33.   2.   3.  27.  36. 314.  14.  44.   2.]
 [  0.  26.   3.   0.  22.   9.  14. 152.   8.   6.]
 [  0.  15.   1.   1.   9.  19.  44.   8.  47.   0.]
 [  0.   5.   0.   0.   1.   0.   2.   6.   0.  46.]]


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. To prevent hanging your computer because of RAM shortage use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [106]:
df = ml_df.copy()
n = df.userId.nunique()
matrix = np.zeros((n+1, n+1))
indices = np.triu_indices_from(matrix)

movies = []
for i in range(1,1001):
    movie_i = df.loc[df['movieId']==i,['userId']]
    movie_i = movie_i['userId'].values.tolist()
    movies.append(movie_i)
    
    
for i in range(1, 1001):
    for j in range(i, n+1):
        common_elements = np.intersect1d(movies[i-1], movies[j-1])
        matrix[i][j] = len(common_elements)
        
i_lower = np.tril_indices(n, -1)
matrix[i_lower] = matrix.T[i_lower] 
        
print(matrix[:10, :10])


[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 215.  68.  32.   2.  32.  58.  32.   5.  12.]
 [  0.  68. 110.  26.   3.  22.  36.  18.   6.   3.]
 [  0.  32.  26.  52.   1.  19.  25.  19.   4.   9.]
 [  0.   2.   3.   1.   7.   3.   2.   6.   1.   0.]
 [  0.  32.  22.  19.   3.  49.  24.  23.   4.   9.]
 [  0.  58.  36.  25.   2.  24. 102.  22.   5.   9.]
 [  0.  32.  18.  19.   6.  23.  22.  54.   4.   5.]
 [  0.   5.   6.   4.   1.   4.   5.   4.   8.   0.]
 [  0.  12.   3.   9.   0.   9.   9.   5.   0.  16.]]
